server.port=8081

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
logging.level.org.springframework.mail=DEBUG
email.verification.token.expiration=15

issuer=Synapse
app.base=http://localhost:8080


jwt.token.access.token.expiry=1800000
jwt.token.refresh.token.expiry=604800000
jwt.keystore.location=/home/rishabh/Synapse/auth-service/src/main/resources/jwtKeystore.jceks
jwt.keystore.password=${JWT_KEYSTORE_PASSWORD}
jwt.key.alias=jwtKey
jwt.key.password=${JWT_KEY_PASSWORD}

spring.data.jdbc.dialect=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/authentication
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update