version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=jdbc:postgresql://postgres:5432/authentication
      - DB_USERNAME=postgres
      - MAIL_HOST=mailhog
      - DB_PASSWORD=postgres
      - TWILIO_ACCOUNT_SID=AC6e0e7cbef200b2fd85c5e8429768041e
      - REDIS_HOST=redis
      - TWILIO_AUTH_TOKEN=6380407c11a0a2fb211353db89297090
      - TWILIO_PATH_SERVICE_ID=VA02b136216de2b87c9c133d72381269e6
      - JWT_KEYSTORE_LOCATION=classpath:keystore.jks
      - JWT_KEYSTORE_PASSWORD=asfj3489urwejjfe4r
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_KEY_PASSWORD=328942urijdfkj()87
    depends_on:
      - postgres
      - redis
      - mailhog
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=authentication
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.0.3-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: